//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustCollectorsPresentation.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysUser", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class SysUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.CustomerDeliveryAddress[] CustomerDeliveryAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateRegisteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.CustomerDeliveryAddress[] CustomerDeliveryAddresses {
            get {
                return this.CustomerDeliveryAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDeliveryAddressesField, value) != true)) {
                    this.CustomerDeliveryAddressesField = value;
                    this.RaisePropertyChanged("CustomerDeliveryAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateRegistered {
            get {
                return this.DateRegisteredField;
            }
            set {
                if ((this.DateRegisteredField.Equals(value) != true)) {
                    this.DateRegisteredField = value;
                    this.RaisePropertyChanged("DateRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDeliveryAddress", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class CustomerDeliveryAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityOrTownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplexOrBuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurburbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.SysUser SysUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityOrTown {
            get {
                return this.CityOrTownField;
            }
            set {
                if ((object.ReferenceEquals(this.CityOrTownField, value) != true)) {
                    this.CityOrTownField = value;
                    this.RaisePropertyChanged("CityOrTown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComplexOrBuilding {
            get {
                return this.ComplexOrBuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplexOrBuildingField, value) != true)) {
                    this.ComplexOrBuildingField = value;
                    this.RaisePropertyChanged("ComplexOrBuilding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientName {
            get {
                return this.RecipientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientNameField, value) != true)) {
                    this.RecipientNameField = value;
                    this.RaisePropertyChanged("RecipientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientPhone {
            get {
                return this.RecipientPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientPhoneField, value) != true)) {
                    this.RecipientPhoneField = value;
                    this.RaisePropertyChanged("RecipientPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street_Address {
            get {
                return this.Street_AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.Street_AddressField, value) != true)) {
                    this.Street_AddressField = value;
                    this.RaisePropertyChanged("Street_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surburb {
            get {
                return this.SurburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SurburbField, value) != true)) {
                    this.SurburbField = value;
                    this.RaisePropertyChanged("Surburb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.SysUser SysUser {
            get {
                return this.SysUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SysUserField, value) != true)) {
                    this.SysUserField = value;
                    this.RaisePropertyChanged("SysUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSessionDetails", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors.Classes")]
    [System.SerializableAttribute()]
    public partial class UserSessionDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.userTypeField, value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPersonalDetails", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors.Classes")]
    [System.SerializableAttribute()]
    public partial class UserPersonalDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAddress", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors.Classes")]
    [System.SerializableAttribute()]
    public partial class CustomerAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityOrTownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplexOrBuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityOrTown {
            get {
                return this.CityOrTownField;
            }
            set {
                if ((object.ReferenceEquals(this.CityOrTownField, value) != true)) {
                    this.CityOrTownField = value;
                    this.RaisePropertyChanged("CityOrTown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComplexOrBuilding {
            get {
                return this.ComplexOrBuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplexOrBuildingField, value) != true)) {
                    this.ComplexOrBuildingField = value;
                    this.RaisePropertyChanged("ComplexOrBuilding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientName {
            get {
                return this.RecipientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientNameField, value) != true)) {
                    this.RecipientNameField = value;
                    this.RaisePropertyChanged("RecipientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientPhone {
            get {
                return this.RecipientPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientPhoneField, value) != true)) {
                    this.RecipientPhoneField = value;
                    this.RaisePropertyChanged("RecipientPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress {
            get {
                return this.StreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressField, value) != true)) {
                    this.StreetAddressField = value;
                    this.RaisePropertyChanged("StreetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAddressInsert", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors.Classes")]
    [System.SerializableAttribute()]
    public partial class CustomerAddressInsert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityOrTownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplexOrBuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityOrTown {
            get {
                return this.CityOrTownField;
            }
            set {
                if ((object.ReferenceEquals(this.CityOrTownField, value) != true)) {
                    this.CityOrTownField = value;
                    this.RaisePropertyChanged("CityOrTown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComplexOrBuilding {
            get {
                return this.ComplexOrBuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplexOrBuildingField, value) != true)) {
                    this.ComplexOrBuildingField = value;
                    this.RaisePropertyChanged("ComplexOrBuilding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientName {
            get {
                return this.RecipientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientNameField, value) != true)) {
                    this.RecipientNameField = value;
                    this.RaisePropertyChanged("RecipientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientPhone {
            get {
                return this.RecipientPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientPhoneField, value) != true)) {
                    this.RecipientPhoneField = value;
                    this.RaisePropertyChanged("RecipientPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress {
            get {
                return this.StreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressField, value) != true)) {
                    this.StreetAddressField = value;
                    this.RaisePropertyChanged("StreetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class Gender : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Shoe[] ShoesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgeGroup {
            get {
                return this.AgeGroupField;
            }
            set {
                if ((this.AgeGroupField.Equals(value) != true)) {
                    this.AgeGroupField = value;
                    this.RaisePropertyChanged("AgeGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Shoe[] Shoes {
            get {
                return this.ShoesField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoesField, value) != true)) {
                    this.ShoesField = value;
                    this.RaisePropertyChanged("Shoes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shoe", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class Shoe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColourWayIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Colourway ColourwayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiscountPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.ShoeVariant[] ShoeVariantsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColourWayID {
            get {
                return this.ColourWayIDField;
            }
            set {
                if ((this.ColourWayIDField.Equals(value) != true)) {
                    this.ColourWayIDField = value;
                    this.RaisePropertyChanged("ColourWayID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Colourway Colourway {
            get {
                return this.ColourwayField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourwayField, value) != true)) {
                    this.ColourwayField = value;
                    this.RaisePropertyChanged("Colourway");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountPercentage {
            get {
                return this.DiscountPercentageField;
            }
            set {
                if ((this.DiscountPercentageField.Equals(value) != true)) {
                    this.DiscountPercentageField = value;
                    this.RaisePropertyChanged("DiscountPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenderId {
            get {
                return this.GenderIdField;
            }
            set {
                if ((this.GenderIdField.Equals(value) != true)) {
                    this.GenderIdField = value;
                    this.RaisePropertyChanged("GenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.ShoeVariant[] ShoeVariants {
            get {
                return this.ShoeVariantsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoeVariantsField, value) != true)) {
                    this.ShoeVariantsField = value;
                    this.RaisePropertyChanged("ShoeVariants");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Colourway", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class Colourway : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Shoe[] ShoesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Shoe[] Shoes {
            get {
                return this.ShoesField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoesField, value) != true)) {
                    this.ShoesField = value;
                    this.RaisePropertyChanged("Shoes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Brand BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Shoe[] ShoesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Brand Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Shoe[] Shoes {
            get {
                return this.ShoesField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoesField, value) != true)) {
                    this.ShoesField = value;
                    this.RaisePropertyChanged("Shoes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoeVariant", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class ShoeVariant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateActivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainImgURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QTYInStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Shoe ShoeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShoeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.ShoeSize ShoeSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateActivated {
            get {
                return this.DateActivatedField;
            }
            set {
                if ((this.DateActivatedField.Equals(value) != true)) {
                    this.DateActivatedField = value;
                    this.RaisePropertyChanged("DateActivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeactivated {
            get {
                return this.DateDeactivatedField;
            }
            set {
                if ((this.DateDeactivatedField.Equals(value) != true)) {
                    this.DateDeactivatedField = value;
                    this.RaisePropertyChanged("DateDeactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainImgURL {
            get {
                return this.MainImgURLField;
            }
            set {
                if ((object.ReferenceEquals(this.MainImgURLField, value) != true)) {
                    this.MainImgURLField = value;
                    this.RaisePropertyChanged("MainImgURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QTYInStock {
            get {
                return this.QTYInStockField;
            }
            set {
                if ((this.QTYInStockField.Equals(value) != true)) {
                    this.QTYInStockField = value;
                    this.RaisePropertyChanged("QTYInStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Shoe Shoe {
            get {
                return this.ShoeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoeField, value) != true)) {
                    this.ShoeField = value;
                    this.RaisePropertyChanged("Shoe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShoeId {
            get {
                return this.ShoeIdField;
            }
            set {
                if ((this.ShoeIdField.Equals(value) != true)) {
                    this.ShoeIdField = value;
                    this.RaisePropertyChanged("ShoeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.ShoeSize ShoeSize {
            get {
                return this.ShoeSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoeSizeField, value) != true)) {
                    this.ShoeSizeField = value;
                    this.RaisePropertyChanged("ShoeSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeID {
            get {
                return this.SizeIDField;
            }
            set {
                if ((this.SizeIDField.Equals(value) != true)) {
                    this.SizeIDField = value;
                    this.RaisePropertyChanged("SizeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Brand", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class Brand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainLogoURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeactivated {
            get {
                return this.DateDeactivatedField;
            }
            set {
                if ((this.DateDeactivatedField.Equals(value) != true)) {
                    this.DateDeactivatedField = value;
                    this.RaisePropertyChanged("DateDeactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainLogoURL {
            get {
                return this.MainLogoURLField;
            }
            set {
                if ((object.ReferenceEquals(this.MainLogoURLField, value) != true)) {
                    this.MainLogoURLField = value;
                    this.RaisePropertyChanged("MainLogoURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Category[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Category Category1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SuperCategoryIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Category[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Category Category1 {
            get {
                return this.Category1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Category1Field, value) != true)) {
                    this.Category1Field = value;
                    this.RaisePropertyChanged("Category1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SuperCategoryID {
            get {
                return this.SuperCategoryIDField;
            }
            set {
                if ((this.SuperCategoryIDField.Equals(value) != true)) {
                    this.SuperCategoryIDField = value;
                    this.RaisePropertyChanged("SuperCategoryID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoeSize", Namespace="http://schemas.datacontract.org/2004/07/DustCollectors")]
    [System.SerializableAttribute()]
    public partial class ShoeSize : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DustCollectorsPresentation.ServiceReference1.ShoeVariant[] ShoeVariantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SizeTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DustCollectorsPresentation.ServiceReference1.ShoeVariant[] ShoeVariants {
            get {
                return this.ShoeVariantsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoeVariantsField, value) != true)) {
                    this.ShoeVariantsField = value;
                    this.RaisePropertyChanged("ShoeVariants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SizeTag {
            get {
                return this.SizeTagField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeTagField, value) != true)) {
                    this.SizeTagField = value;
                    this.RaisePropertyChanged("SizeTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string System {
            get {
                return this.SystemField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemField, value) != true)) {
                    this.SystemField = value;
                    this.RaisePropertyChanged("System");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsReg", ReplyAction="http://tempuri.org/IService1/IsRegResponse")]
        bool IsReg(DustCollectorsPresentation.ServiceReference1.SysUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsReg", ReplyAction="http://tempuri.org/IService1/IsRegResponse")]
        System.Threading.Tasks.Task<bool> IsRegAsync(DustCollectorsPresentation.ServiceReference1.SysUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserSessionDetails", ReplyAction="http://tempuri.org/IService1/GetUserSessionDetailsResponse")]
        DustCollectorsPresentation.ServiceReference1.UserSessionDetails GetUserSessionDetails(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserSessionDetails", ReplyAction="http://tempuri.org/IService1/GetUserSessionDetailsResponse")]
        System.Threading.Tasks.Task<DustCollectorsPresentation.ServiceReference1.UserSessionDetails> GetUserSessionDetailsAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserDetails", ReplyAction="http://tempuri.org/IService1/GetUserDetailsResponse")]
        DustCollectorsPresentation.ServiceReference1.UserPersonalDetails GetUserDetails(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserDetails", ReplyAction="http://tempuri.org/IService1/GetUserDetailsResponse")]
        System.Threading.Tasks.Task<DustCollectorsPresentation.ServiceReference1.UserPersonalDetails> GetUserDetailsAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserPassword", ReplyAction="http://tempuri.org/IService1/GetUserPasswordResponse")]
        string GetUserPassword(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserPassword", ReplyAction="http://tempuri.org/IService1/GetUserPasswordResponse")]
        System.Threading.Tasks.Task<string> GetUserPasswordAsync(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerAddresses", ReplyAction="http://tempuri.org/IService1/GetCustomerAddressesResponse")]
        DustCollectorsPresentation.ServiceReference1.CustomerAddress[] GetCustomerAddresses(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerAddresses", ReplyAction="http://tempuri.org/IService1/GetCustomerAddressesResponse")]
        System.Threading.Tasks.Task<DustCollectorsPresentation.ServiceReference1.CustomerAddress[]> GetCustomerAddressesAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAddress", ReplyAction="http://tempuri.org/IService1/InsertAddressResponse")]
        bool InsertAddress(DustCollectorsPresentation.ServiceReference1.CustomerAddressInsert address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAddress", ReplyAction="http://tempuri.org/IService1/InsertAddressResponse")]
        System.Threading.Tasks.Task<bool> InsertAddressAsync(DustCollectorsPresentation.ServiceReference1.CustomerAddressInsert address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCustomerAddress", ReplyAction="http://tempuri.org/IService1/getCustomerAddressResponse")]
        DustCollectorsPresentation.ServiceReference1.CustomerAddress getCustomerAddress(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCustomerAddress", ReplyAction="http://tempuri.org/IService1/getCustomerAddressResponse")]
        System.Threading.Tasks.Task<DustCollectorsPresentation.ServiceReference1.CustomerAddress> getCustomerAddressAsync(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGender", ReplyAction="http://tempuri.org/IService1/InsertGenderResponse")]
        bool InsertGender(DustCollectorsPresentation.ServiceReference1.Gender newGender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGender", ReplyAction="http://tempuri.org/IService1/InsertGenderResponse")]
        System.Threading.Tasks.Task<bool> InsertGenderAsync(DustCollectorsPresentation.ServiceReference1.Gender newGender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertShoeColourway", ReplyAction="http://tempuri.org/IService1/InsertShoeColourwayResponse")]
        bool InsertShoeColourway(DustCollectorsPresentation.ServiceReference1.Colourway newColourway);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertShoeColourway", ReplyAction="http://tempuri.org/IService1/InsertShoeColourwayResponse")]
        System.Threading.Tasks.Task<bool> InsertShoeColourwayAsync(DustCollectorsPresentation.ServiceReference1.Colourway newColourway);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertShoeCategory", ReplyAction="http://tempuri.org/IService1/InsertShoeCategoryResponse")]
        bool InsertShoeCategory(DustCollectorsPresentation.ServiceReference1.Category newCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertShoeCategory", ReplyAction="http://tempuri.org/IService1/InsertShoeCategoryResponse")]
        System.Threading.Tasks.Task<bool> InsertShoeCategoryAsync(DustCollectorsPresentation.ServiceReference1.Category newCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertShoeSize", ReplyAction="http://tempuri.org/IService1/InsertShoeSizeResponse")]
        bool InsertShoeSize(DustCollectorsPresentation.ServiceReference1.ShoeSize newShoeSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertShoeSize", ReplyAction="http://tempuri.org/IService1/InsertShoeSizeResponse")]
        System.Threading.Tasks.Task<bool> InsertShoeSizeAsync(DustCollectorsPresentation.ServiceReference1.ShoeSize newShoeSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertProduct", ReplyAction="http://tempuri.org/IService1/InsertProductResponse")]
        bool InsertProduct(DustCollectorsPresentation.ServiceReference1.Product newProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertProduct", ReplyAction="http://tempuri.org/IService1/InsertProductResponse")]
        System.Threading.Tasks.Task<bool> InsertProductAsync(DustCollectorsPresentation.ServiceReference1.Product newProduct);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DustCollectorsPresentation.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DustCollectorsPresentation.ServiceReference1.IService1>, DustCollectorsPresentation.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsReg(DustCollectorsPresentation.ServiceReference1.SysUser user) {
            return base.Channel.IsReg(user);
        }
        
        public System.Threading.Tasks.Task<bool> IsRegAsync(DustCollectorsPresentation.ServiceReference1.SysUser user) {
            return base.Channel.IsRegAsync(user);
        }
        
        public DustCollectorsPresentation.ServiceReference1.UserSessionDetails GetUserSessionDetails(string email, string password) {
            return base.Channel.GetUserSessionDetails(email, password);
        }
        
        public System.Threading.Tasks.Task<DustCollectorsPresentation.ServiceReference1.UserSessionDetails> GetUserSessionDetailsAsync(string email, string password) {
            return base.Channel.GetUserSessionDetailsAsync(email, password);
        }
        
        public DustCollectorsPresentation.ServiceReference1.UserPersonalDetails GetUserDetails(int Id) {
            return base.Channel.GetUserDetails(Id);
        }
        
        public System.Threading.Tasks.Task<DustCollectorsPresentation.ServiceReference1.UserPersonalDetails> GetUserDetailsAsync(int Id) {
            return base.Channel.GetUserDetailsAsync(Id);
        }
        
        public string GetUserPassword(int UserId) {
            return base.Channel.GetUserPassword(UserId);
        }
        
        public System.Threading.Tasks.Task<string> GetUserPasswordAsync(int UserId) {
            return base.Channel.GetUserPasswordAsync(UserId);
        }
        
        public DustCollectorsPresentation.ServiceReference1.CustomerAddress[] GetCustomerAddresses(int userID) {
            return base.Channel.GetCustomerAddresses(userID);
        }
        
        public System.Threading.Tasks.Task<DustCollectorsPresentation.ServiceReference1.CustomerAddress[]> GetCustomerAddressesAsync(int userID) {
            return base.Channel.GetCustomerAddressesAsync(userID);
        }
        
        public bool InsertAddress(DustCollectorsPresentation.ServiceReference1.CustomerAddressInsert address) {
            return base.Channel.InsertAddress(address);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAddressAsync(DustCollectorsPresentation.ServiceReference1.CustomerAddressInsert address) {
            return base.Channel.InsertAddressAsync(address);
        }
        
        public DustCollectorsPresentation.ServiceReference1.CustomerAddress getCustomerAddress(int customerID) {
            return base.Channel.getCustomerAddress(customerID);
        }
        
        public System.Threading.Tasks.Task<DustCollectorsPresentation.ServiceReference1.CustomerAddress> getCustomerAddressAsync(int customerID) {
            return base.Channel.getCustomerAddressAsync(customerID);
        }
        
        public bool InsertGender(DustCollectorsPresentation.ServiceReference1.Gender newGender) {
            return base.Channel.InsertGender(newGender);
        }
        
        public System.Threading.Tasks.Task<bool> InsertGenderAsync(DustCollectorsPresentation.ServiceReference1.Gender newGender) {
            return base.Channel.InsertGenderAsync(newGender);
        }
        
        public bool InsertShoeColourway(DustCollectorsPresentation.ServiceReference1.Colourway newColourway) {
            return base.Channel.InsertShoeColourway(newColourway);
        }
        
        public System.Threading.Tasks.Task<bool> InsertShoeColourwayAsync(DustCollectorsPresentation.ServiceReference1.Colourway newColourway) {
            return base.Channel.InsertShoeColourwayAsync(newColourway);
        }
        
        public bool InsertShoeCategory(DustCollectorsPresentation.ServiceReference1.Category newCategory) {
            return base.Channel.InsertShoeCategory(newCategory);
        }
        
        public System.Threading.Tasks.Task<bool> InsertShoeCategoryAsync(DustCollectorsPresentation.ServiceReference1.Category newCategory) {
            return base.Channel.InsertShoeCategoryAsync(newCategory);
        }
        
        public bool InsertShoeSize(DustCollectorsPresentation.ServiceReference1.ShoeSize newShoeSize) {
            return base.Channel.InsertShoeSize(newShoeSize);
        }
        
        public System.Threading.Tasks.Task<bool> InsertShoeSizeAsync(DustCollectorsPresentation.ServiceReference1.ShoeSize newShoeSize) {
            return base.Channel.InsertShoeSizeAsync(newShoeSize);
        }
        
        public bool InsertProduct(DustCollectorsPresentation.ServiceReference1.Product newProduct) {
            return base.Channel.InsertProduct(newProduct);
        }
        
        public System.Threading.Tasks.Task<bool> InsertProductAsync(DustCollectorsPresentation.ServiceReference1.Product newProduct) {
            return base.Channel.InsertProductAsync(newProduct);
        }
    }
}
